apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    container.stack.gov.sg/instance: cstack-crossplane
  name: cssmtpusers.crd.aws.container.stack.gov.sg
spec:
  conversion:
    strategy: None
  group: crd.aws.container.stack.gov.sg
  names:
    categories:
      - cstack
      - claim
    kind: CSSMTPUser
    listKind: CSSMTPUserList
    plural: cssmtpusers
    singular: cssmtpuser
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Name of the managed resource.
          jsonPath: .metadata.annotations.ses-smtp/identity
          name: Domain/Email
          type: string
        - description: Specifies what will happen to the underlying external when this managed resource is deleted.
          jsonPath: .spec.parameters.deletionPolicy
          name: Deletion Policy
          type: string
        - jsonPath: .status.conditions[?(@.type=='Synced')].status
          name: SYNCED
          type: string
        - jsonPath: .status.conditions[?(@.type=='Ready')].status
          name: READY
          type: string
        - jsonPath: .spec.writeConnectionSecretToRef.name
          name: CONNECTION-SECRET
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: AGE
          type: date
      name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                compositeDeletePolicy:
                  default: Background
                  enum:
                    - Background
                    - Foreground
                  type: string
                compositionRef:
                  properties:
                    name:
                      type: string
                  required:
                    - name
                  type: object
                compositionRevisionRef:
                  properties:
                    name:
                      type: string
                  required:
                    - name
                  type: object
                compositionSelector:
                  properties:
                    matchLabels:
                      additionalProperties:
                        type: string
                      type: object
                  required:
                    - matchLabels
                  type: object
                compositionUpdatePolicy:
                  default: Automatic
                  enum:
                    - Automatic
                    - Manual
                  type: string
                parameters:
                  properties:
                    accessKeyStatus:
                      default: Active
                      description: Status of the Access Key
                      enum:
                        - Active
                        - Inactive
                      type: string
                    configurationSetName:
                      default: ""
                      description: Name of SES Configuration Set
                      type: string
                    deletionPolicy:
                      default: Orphan
                      description: Specifies whether to allow the actual Managed Resource to be deleted.
                      enum:
                        - Delete
                        - Orphan
                      type: string
                    domainOrEmail:
                      description: Domain or Email of the SES Identity
                      type: string
                    templateName:
                      default: ""
                      description: Name of SES Email Template
                      type: string
                  required:
                    - domainOrEmail
                  type: object
                publishConnectionDetailsTo:
                  properties:
                    configRef:
                      default:
                        name: default
                      properties:
                        name:
                          type: string
                      type: object
                    metadata:
                      properties:
                        annotations:
                          additionalProperties:
                            type: string
                          type: object
                        labels:
                          additionalProperties:
                            type: string
                          type: object
                        type:
                          type: string
                      type: object
                    name:
                      type: string
                  required:
                    - name
                  type: object
                resourceRef:
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                  required:
                    - apiVersion
                    - kind
                    - name
                  type: object
                writeConnectionSecretToRef:
                  properties:
                    name:
                      type: string
                  required:
                    - name
                  type: object
              required:
                - parameters
              type: object
            status:
              properties:
                conditions:
                  description: Conditions of the resource.
                  items:
                    properties:
                      lastTransitionTime:
                        format: date-time
                        type: string
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                    required:
                      - lastTransitionTime
                      - reason
                      - status
                      - type
                    type: object
                  type: array
                connectionDetails:
                  properties:
                    lastPublishedTime:
                      format: date-time
                      type: string
                  type: object
                parameters:
                  properties:
                    iamKey:
                      description: The Secret Object name for IAM Access Key.
                      type: string
                    smtpKey:
                      description: The Secret Object name for SMTP Credential Key.
                      type: string
                  type: object
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
      subresources:
        status: {}
